### ISSUE TITLE
runtime panic

### ISSUE THREAD

**Issue by gaoyifan** [knight42/Yuki#21]
mirrors.cat.net 突然挂掉了。看日志，似乎和xfs文件系统获取尺寸的代码有关。

```
42:49 mirror-jp yukid[28977]: panic: runtime error: index out of range
Jan 22 01:42:49 mirror-jp yukid[28977]: goroutine 518685 [running]:
Jan 22 01:42:49 mirror-jp yukid[28977]: github.com/knight42/Yuki/fs.(*xfs).GetSize(0xedce90, 0xc0000d4460, 0x11, 0x564d67)
Jan 22 01:42:49 mirror-jp yukid[28977]:         /home/travis/gopath/src/github.com/knight42/Yuki/fs/fs.go:97 +0x3fd
Jan 22 01:42:49 mirror-jp yukid[28977]: github.com/knight42/Yuki/core.(*Core).UpsertRepoMeta(0xc0000df9a0, 0xc0002b4944, 0x6, 0xc0000d4460, 0x11, 0xa, 0x0, 0x
Jan 22 01:42:49 mirror-jp yukid[28977]:         /home/travis/gopath/src/github.com/knight42/Yuki/core/meta.go:148 +0x9c
Jan 22 01:42:49 mirror-jp yukid[28977]: github.com/knight42/Yuki/server.(*Server).hookPostSync.func1(0x1, 0xc0004e9470)
Jan 22 01:42:49 mirror-jp yukid[28977]:         /home/travis/gopath/src/github.com/knight42/Yuki/server/hooks.go:34 +0x4f7
Jan 22 01:42:49 mirror-jp yukid[28977]: created by github.com/knight42/Yuki/events.(*Emitter).Emit
Jan 22 01:42:49 mirror-jp yukid[28977]:         /home/travis/gopath/src/github.com/knight42/Yuki/events/main.go:68 +0x9a
Jan 22 01:42:49 mirror-jp systemd[1]: yukid.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 22 01:42:49 mirror-jp systemd[1]: yukid.service: Failed with result 'exit-code'.
```

**Comment by knight42** [comment]
@gaoyifan 能告诉我一下 `sudo -n xfs_quota -c 'quota -pN <repo>'` 的输出吗？

**Comment by gaoyifan** [comment]
新版 xfs 的用户态接口似乎发生了变化，`quota` 命令无法获取仓库尺寸了。
```
$ sudo -n xfs_quota -c 'quota -pN debian'
/dev/sda4           1677145364          0          0   00 [--------] /srv
/dev/sda4           1677145364          0          0   00 [--------] /srv
```

我在新版文档中只找到一条与project尺寸相关的命令 `df` ，且只能一次性列出所有project的尺寸：
```
$ sudo -n xfs_quota -c 'df'
Filesystem           1K-blocks       Used  Available  Use% Pathname
/dev/sda3             48804576     486800   48317776    1% /var/log
/dev/sda4           5904669696 4233998128 1670671568   72% /srv
/dev/sda4           5904669696   10010840 1670671568    0% /srv/repo
/dev/sda4           5904669696  126305260 1670671568    2% /srv/repo/centos
/dev/sda4           5904669696 1681975628 1670671568   28% /srv/repo/debian
/dev/sda4           5904669696   46122244 1670671568    1% /srv/repo/archlinux
/dev/sda4           5904669696  157990432 1670671568    3% /srv/repo/debian-security
/dev/sda4           5904669696 1279402480 1670671568   22% /srv/repo/ubuntu
/dev/sda4           5904669696  376161512 1670671568    6% /srv/repo/fedora
/dev/sda4           5904669696  183778104 1670671568    3% /srv/repo/epel
/dev/sda4           5904669696    4478564 1670671568    0% /srv/repo/sury
/dev/sda4           5904669696   63918780 1670671568    1% /srv/repo/archlinuxcn
/dev/sda4           5904669696   87634092 1670671568    1% /srv/repo/proxmox
/dev/sda4           5904669696  207945444 1670671568    4% /srv/repo/ros
/dev/sda4           5904669696      24552 1670671568    0% /srv/repo/sb
/dev/sda4           5904669696          0 1670671568    0% /srv/repo/cdnjs
/dev/sda4           5904669696          0 1670671568    0% /srv/repo/deepin
/dev/sda2             47799020    4655500   43143520   10% /
/dev/sda1               944120      62052     882068    7% /boot
Filesystem           1K-blocks       Used  Available  Use% Pathname
/dev/sda3             48804576     486800   48317776    1% /var/log
/dev/sda4           5904669696 4233998128 1670671568   72% /srv
/dev/sda4           5904669696   10010840 1670671568    0% /srv/repo
/dev/sda4           5904669696  126305260 1670671568    2% /srv/repo/centos
/dev/sda4           5904669696 1681975628 1670671568   28% /srv/repo/debian
/dev/sda4           5904669696   46122244 1670671568    1% /srv/repo/archlinux
/dev/sda4           5904669696  157990432 1670671568    3% /srv/repo/debian-security
/dev/sda4           5904669696 1279402480 1670671568   22% /srv/repo/ubuntu
/dev/sda4           5904669696  376161512 1670671568    6% /srv/repo/fedora
/dev/sda4           5904669696  183778104 1670671568    3% /srv/repo/epel
/dev/sda4           5904669696    4478564 1670671568    0% /srv/repo/sury
/dev/sda4           5904669696   63918780 1670671568    1% /srv/repo/archlinuxcn
/dev/sda4           5904669696   87634092 1670671568    1% /srv/repo/proxmox
/dev/sda4           5904669696  207945444 1670671568    4% /srv/repo/ros
/dev/sda4           5904669696      24552 1670671568    0% /srv/repo/sb
/dev/sda4           5904669696          0 1670671568    0% /srv/repo/cdnjs
/dev/sda4           5904669696          0 1670671568    0% /srv/repo/deepin
/dev/sda2             47799020    4655500   43143520   10% /
/dev/sda1               944120      62052     882068    7% /boot
```

**Comment by knight42** [comment]
@gaoyifan 凉凉

**Comment by knight42** [comment]
@gaoyifan 那要不我先禁用掉 xfs 获取 size 的功能？

**Comment by gaoyifan** [comment]
嗯，这也是一个workaround吧。 可以不用做代码级的修改，我把`/etc/yuki/daemon.toml` 改成了
```
fs = "default"
```

**Comment by knight42** [comment]
😂
